CREATE TABLE [dbo].[Item]
(
	[ItemCode] nvarchar(50) NOT NULL PRIMARY KEY,
	ItemTile nvarchar(max) not null,
	ItemDescription text not null,
	UnitPrice decimal(10,2) not null,
	ChageTax bit not null,
	Stock int not null,
	ItemStatus int not null,
	ItemType int not null,
	Material int not null,
	Category int not null,
	SubCategory int null,
	ManagedByOptions bit not null,
	Size nvarchar(10) not null,
	ColorName nvarchar(100) null,
	ColorCode nvarchar(100) null,
	CreatedBy nvarchar(200) not null,
	CreatedAt datetime not null,
	UpdatedAt datetime not null,
	foreign key(ItemStatus) references ItemStatus(Id),
	foreign key(ItemType) references ItemTypeCat(Id),
	foreign key(Material) references ItemMaterialCat(Id),
	foreign key(Category) references ItemCategoryCat(Id),
	foreign key(SubCategory) references ItemCategoryCat(Id),
)
